spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 500MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    serialization: {write-dates-as-timestamps: true}
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.100.17.12:3306/star_pet?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  # REDIS (RedisProperties)
  redis:
    database: 0
    timeout: 5000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

# 文件地址
file:
  url: D:\\

#解决缓存目录被系统清除的问题 稳定版暂未配置
server:
  tomcat:
    basedir: ./tmp
##自定义配置
taskmagprops:
  expireTime: 18000000
  checkLoginUrl: /jl/modal/add;/jl/modal/update;/jl/modal/delete;/jl/modal/list;/jl/user/getTokenUser
  filedir: api-mag/
  fileBasePath: upload/

wx:
  #微信小程序
  miniapp:
    configs:
    - appid: wx75818434691f4bd9 #微信公众号或者小程序等的appid
      secret: c1713ae64b8a76329aff3f7c4a6521d6
      msgDataFormat: JSON

logging:
  level:
    com:
      company:
        project:
          dao: DEBUG
